micronaut:
  application:
    name: parkhaus-manager-micronaut
  server:
    port: 8280

jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    writeDatesAsTimestamps: false

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

parkhaus:
  gebuehr: 2
  toleranceBtwPaymentAndExit: 30