FROM maven:3.6.3-openjdk-11 as maven
COPY . /home/app/parkhaus-manager
WORKDIR /home/app/parkhaus-manager
RUN mvn -ntp install

FROM oracle/graalvm-ce:20.1.0-java11
COPY --from=maven /home/app/parkhaus-manager/target/lib/* /deployments/lib/
COPY --from=maven /home/app/parkhaus-manager/target/*-runner.jar /deployments/app.jar
EXPOSE 8180
ENTRYPOINT ["java","-jar","/deployments/app.jar"]